### ISSUE TITLE
pip install command fails

### ISSUE THREAD

**Issue by simpsus** [jefferythewind/scikit-learn-erasplit#3]
this is a blank environment (did not want to taint my sklearn install) with python 3.11 and nothing more installed. 
The output of `pip install .` gives
```

(era_splitting) PS E:\github\scikit-learn-erasplit> pip install .
Processing e:\github\scikit-learn-erasplit
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\grumb\miniconda3\envs\era_splitting\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\grumb\miniconda3\envs\era_splitting\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\grumb\miniconda3\envs\era_splitting\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\grumb\AppData\Local\Temp\pip-build-env-bd96avh_\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\grumb\AppData\Local\Temp\pip-build-env-bd96avh_\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\grumb\AppData\Local\Temp\pip-build-env-bd96avh_\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\grumb\AppData\Local\Temp\pip-build-env-bd96avh_\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 35, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jefferythewind** [comment]
OK thanks for this. I will put together the list of required software versions and a script to install it all in a fresh conda environment. Please standby.

**Comment by jefferythewind** [comment]
Wow I'm seeing this error as well when trying to install into a new environment. I'll update shortly.

**Comment by jefferythewind** [comment]
OK the problem was that I renamed the README.rst file to README.md and I didn't realize that would break installation. Apparenlty you need to have the .rst file ending for the packaged to work with PIP. Anyways I put back the .rst file and installation now works.
